### ISSUE TITLE
Database and model ukbb_neuronet_brain_segmentation

### ISSUE THREAD

**Issue by iitzco** [DLTK/models#10]
Regarding the database used to trained this model...
* Is it publicly available? (I've browsed the referenced page but found nothing)
* How can I get access to train own models?

Regarding model, where can I find information about the architecture or the training process?

**Comment by mrajchl** [comment]
Hi,
please refer to the [FAQ](http://www.ukbiobank.ac.uk/ams2-system-faq/) on applying and accessing UK Biobank data. 
To answer your second question, please refer to the paper (see [README.md](https://github.com/DLTK/models/blob/master/ukbb_neuronet_brain_segmentation/README.md)) or the source file implementing the Neuronet architecture (see [neuronet.py](https://github.com/DLTK/models/blob/master/ukbb_neuronet_brain_segmentation/neuronet.py)). It is based on the [residual FCN architecture](https://github.com/DLTK/DLTK/blob/master/dltk/networks/segmentation/fcn.py#L98) found in the main DTLK repo.

HTH,
Martin
