### ISSUE TITLE
OSError: SavedModel file does not exist

### ISSUE THREAD

**Issue by fepegar** [DLTK/models#11]
Hi I'm trying to perform a segmentation using NeuroNet. I guess [these docs](https://github.com/DLTK/models/tree/master/ukbb_neuronet_brain_segmentation#deploy) need to be updated, but reading the `deploy.py` and the example files in the repo I managed to generate my `csv` and `json` files. Here they are:

Config:
```json
{
 "protocols": ["fsl_fast"],
 "num_classes": [4], 
 "model_path": "/tmp/neuronet/models/fsl_fast",
 "out_segm_path": "/tmp/neuronet/out/fsl_fast",
 "learning_rate": 0.001,
 "network": {
     "filters": [16, 32, 64, 128],
     "strides": [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2]],
     "num_residual_units": 2
  }
}
```

CSV:
```csv
id,t1
fer,/home/fernando/Dropbox/MRI/t1.nii.gz
pre,/home/fernando/episurg/pre.nii.gz
intra,/home/fernando/episurg/intra.nii.gz
```

My command:
```shell
python deploy.py \                                             
--verbose \
--csv /tmp/neuronet/test.csv \
--config /tmp/neuronet/config.json
```

The output:
```python-traceback
deploy.py:28: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  na_values=[]).as_matrix()
Loading from /tmp/neuronet/models/fsl_fast/0
Traceback (most recent call last):
  File "deploy.py", line 114, in <module>
    predict(args, config)
  File "deploy.py", line 35, in predict
    my_predictor = predictor.from_saved_model(export_dir)
  File "/home/fernando/miniconda3/envs/dltk/lib/python3.6/site-packages/tensorflow/contrib/predictor/predictor_factories.py", line 129, in from_saved_model
    graph=graph)
  File "/home/fernando/miniconda3/envs/dltk/lib/python3.6/site-packages/tensorflow/contrib/predictor/saved_model_predictor.py", line 156, in __init__
    loader.load(self._session, tags.split(','), export_dir)
  File "/home/fernando/miniconda3/envs/dltk/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 200, in load
    saved_model = _parse_saved_model(export_dir)
  File "/home/fernando/miniconda3/envs/dltk/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 78, in _parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: /tmp/neuronet/models/fsl_fast/0/{saved_model.pbtxt|saved_model.pb}
```

I went to `/tmp/neuronet/models/fsl_fast/0/` and found the file `graph.pbtxt`. I tried renaming it to `saved_model.pbtxt` but that didn't work. I also tried using an older version of TF (1.4), but got the sam error.

Do you have any idea what could be wrong?

**Comment by mrajchl** [comment]
There should be a saved_model.pbtxt in fsl_fast.tar.gz\fsl_fast\0\1513180310, maybe try pointing to this? As far as I remember, it was sufficient with tf v.1.10 to point to the directory as you did above. I assume test.csv has been replaced by the CSV you posted above. 

Another note, there might be an issue running these models on other data. Typically, MR weighted images exhibit quite a large variation between acquisition protocols.

**Comment by fepegar** [comment]
Thanks, I'll try with `fsl_fast/0/1513180310/saved_model.pb` and let you know if it worked.

Maybe I can try histogram matching to the training dataset. Also, should my image be MNI-registered? Would a rigid registration be enough?

**Comment by mrajchl** [comment]
Histogram matching might improve things, yes. Registration is a standard rigid to MNI 1mm isotropic resampling as done in the UK Biobank (c.f. the paper).

**Comment by fepegar** [comment]
Great, thanks!

**Comment by fepegar** [comment]
I modified the model path in `config.json` to:
```json
"model_path": "/tmp/neuronet/models/fsl_fast/0/",
```
and it worked.

I ran it on three MNI-registered images from three different scanners and the segmentations are reasonable. @mrajchl, thanks for your help.

**Comment by nazinga** [comment]
Hello,

I am having a similar problem: I ran train.py on my own data and got all the necessary files in MODEL_PATH. However, this does not provide me with the saved_model.pb file which is necessary in order to run deploy.py. I was wondering if you could share the code as to how to transform the output of train.py into the saved_model.pb. 

Thanks a lot !
