### ISSUE TITLE
Placeholder error in deploy.py (PREDICT mode)

### ISSUE THREAD

**Issue by swaticolab** [DLTK/models#13]
I am getting the below error while running deploy.py i nPREDIT mode:

Loading from Downloads\fetal_brain_segmentation_mri\1511556748
AppData\Local\Continuum\anaconda3\lib\site-packages\dltk\utils.py:157: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  sw_dict = {k: v[slicer] for k, v in padded_dict.items()}
Traceback (most recent call last):
  File "deploy.py", line 127, in <module>
    predict(args)
  File "deploy.py", line 79, in predict
    batch_size=1)[0]
  File "AppData\Local\Continuum\anaconda3\lib\site-packages\dltk\utils.py", line 158, in sliding_window_segmentation_inference
    op_parts = session.run(ops_list, feed_dict=sw_dict)
  File "AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 3, 128, 3, 1) for Tensor 'Placeholder:0', which has shape '(?, 3, 128, 128, 1)'

Can you please help.
Note: I am giving the image in .jpg format.

**Comment by mrajchl** [comment]
Hi, 
generally, you can use jpegs, but I would not recommend this for medical images. Just make sure you have all the important header information you require. If you do not know what I mean, I would recommend the tutorial we have written for the tensorflow blog: https://medium.com/tensorflow/an-introduction-to-biomedical-image-analysis-with-tensorflow-and-dltk-2c25304e7c13 

The error message is clearly stating that you are providing inputs tensors of incorrect (1, 3, 128, 3, 1) dimensions. To explain the tensor dimensions: (batch_size, x, y, z, number_features). The image you are providing is 3x128x3 and the placeholder is expecting 3x128x128. 

Closing this now, as this is not an issue. If you still require help, please come to our gitter chat:
https://gitter.im/DLTK/DLTK

HTH, Martin
