### ISSUE TITLE
HI, I have questions about the training data.

### ISSUE THREAD

**Issue by wanjieaa** [DLTK/models#5]
Thanks for your contribution, can you give more details about how to get the training data? I have tried to looking for it but failed, please give me a hand! Many Thanks！

**Comment by mrajchl** [comment]
Hi there,
please refer to the gitter chat (https://gitter.im/DLTK/DLTK) if you have any questions or email the respective authors of the project (email address should be in the respective README.md file). Since this is neither a bug or issue, I am closing this.
